Add support for span queries
vinted/elasticsearch-dsl-rs pull request #141
Opened 2022-06-15 20:12 UTC by jenrik

Adds support for Elasticsearch's span queries, https://www.elastic.co/guide/en/elasticsearch/reference/current/span-queries.html

This PR is still a work-in-progress.

Closes #100

2022-06-27 08:12 UTC, buinauskas commented on src/search/queries/span/span_term.rs
> +impl Serialize for SpanTermQuery {
You could delegate this to the `KeyValue` helper.

https://github.com/vinted/elasticsearch-dsl-rs/blob/master/src/util/key_value_pair.rs

2022-06-27 08:12 UTC, buinauskas commented on src/search/queries/span/span_term.rs
> +}
GitHub is picky about newline feeds, do you mind adding them? I belive that `cargo fmt` should do the job.

2022-06-27 08:13 UTC, buinauskas commented on src/search/queries/span/span_query.rs
> +macro_rules! span_query {
I would probably move this to the `src/search/queries/span/mod.rs` file. At least that's the pattern I've followed with all of the queries.

2022-06-27 08:14 UTC, buinauskas commented on src/search/queries/span/span_not.rs
> +    exclude: Vec<SpanQuery>,
Can excludes/includes be empty? If so, you could also annotate these with `#[serde(skip_serializing_if = "ShouldSkip::should_skip")]`

2022-06-27 08:15 UTC, buinauskas commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
I'd remove this constructor entirely and leave query construction in `Query` enum only.

2022-06-27 08:15 UTC, buinauskas commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
Make sure to make this public.

2022-06-27 08:16 UTC, buinauskas commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
I would remove Box from the arguments and Box these span queries inside the constructor.

2022-06-27 08:16 UTC, buinauskas commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
Instead of accepting an exact SpanQuery, you could accept anything that implements `Into<SpanQuery>` to make public API more user-friendly.

2022-06-27 08:19 UTC, buinauskas commented
First of all, thank you for contributing! You're really on a good track, I've left some comments and suggestions.

2022-06-29 21:20 UTC, jenrik commented on src/search/queries/span/span_term.rs
> +}
I have ran all new files through `cargo fmt`. Let me know if that fixes it

2022-06-29 21:27 UTC, jenrik commented on src/search/queries/span/span_query.rs
> +macro_rules! span_query {
fixed in 550021227bf2c043682fee3c1f11accf5402b2dd

2022-06-29 21:38 UTC, jenrik commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
changed in 27e7364920958a5120b1e200246cd343aeb72f93

2022-06-29 21:43 UTC, jenrik commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
fixed query constructor methods not being public, b7e4ea97c3ee4e04b94cebc7d126752ce2bd997e

2022-06-29 21:55 UTC, jenrik commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
changed in ed1b98d7671556b46c07c428b8cf2323f56ee4f7

2022-06-30 05:04 UTC, buinauskas commented on src/search/queries/mod.rs
> +    ($($variant:ident($query:ty)),+ $(,)?) => {
Not to myself that I should make `query` macro reusable. It's fine for this PR.

2022-06-30 05:11 UTC, buinauskas requested changes

2022-06-30 05:11 UTC, buinauskas commented on src/search/queries/span/span_containing_query.rs
> +    #[allow(unused)]
I think you can drop the `#[allow(unused)]` attribute, public methods should not complain.

2022-06-30 05:11 UTC, buinauskas commented on src/search/queries/span/span_containing_query.rs
> +    pub fn span_containing(little: SpanQuery, big: SpanQuery) -> SpanContainingQuery {
As in the previous suggestions, accept anything that can be converted into a span query, e.g.
```rust
impl Query {
    /// Creates an instance of [`SpanContainingQuery`]
    pub fn span_containing<L, B>(little: L, big: B) -> SpanContainingQuery
    where
        L: Into<SpanQuery>,
        G: Into<SpanQuery>,
    {
        SpanContainingQuery {
            inner: Inner {
                little: Box::new(little.into()),
                big: Box::new(big.into()),
            },
        }
    }
}
```

2022-06-30 05:11 UTC, buinauskas commented on src/search/queries/span/span_near.rs
> +/// TODO
With the documentation comments. I was not trying too hard. I took the official docs and inlined them here.

2022-06-30 05:11 UTC, buinauskas commented on src/search/queries/span/span_near.rs
> +impl ShouldSkip for SpanNearQuery {}
I see the query can have no clauses, it would probably make sense to impl ShouldSkip to skip such queries, 
```rs
impl ShouldSkip for SpanNearQuery {
    fn should_skip(&self) -> bool {
        self.inner.clauses.should_skip()
    }
}
```

2022-06-30 05:11 UTC, buinauskas commented on src/search/queries/span/span_near.rs
> +    pub fn span_near(clauses: Vec<Query>, in_order: Option<bool>, slop: Option<i32>) -> SpanNearQuery {
I see that in_order and slop are optional fields. Default them to `None` in the constructor and create separate methods to set them. I followed the same pattern for other query builders.

2022-07-01 10:43 UTC, jenrik commented on src/search/queries/span/span_containing_query.rs
> +    fn span_containing(little: Box<SpanQuery>, big: Box<SpanQuery>) -> SpanContainingQuery {
I have changed it for function call that take a single `Query`, but I have not found a way to allow `Vec<Into<Query>>`  such that the vector can contain multiple different types.

68960282548206fbe16ecbe7c1c91d01f093a50f

2022-07-01 10:46 UTC, jenrik commented on src/search/queries/span/span_containing_query.rs
> +    #[allow(unused)]
It does complain when I try to run tests, and I haven't been able to find a way to get it to accept without the explicit annotation. Input on how to solve it is highly appreciated.

2022-07-01 10:46 UTC, jenrik commented on src/search/queries/span/span_containing_query.rs
> +    pub fn span_containing(little: SpanQuery, big: SpanQuery) -> SpanContainingQuery {
Fixed in 68960282548206fbe16ecbe7c1c91d01f093a50f

2022-07-01 10:47 UTC, jenrik commented on src/search/queries/span/span_near.rs
> +/// TODO
I will not be including the official docs as I don't know if I have the legal right to redistribute them

2022-07-01 10:51 UTC, jenrik commented on src/search/queries/span/span_near.rs
> +impl ShouldSkip for SpanNearQuery {}
Implemented in e259979f554296f2c86c1af663b61b8713311538

2022-07-01 10:57 UTC, jenrik commented on src/search/queries/span/span_near.rs
> +    pub fn span_near(clauses: Vec<Query>, in_order: Option<bool>, slop: Option<i32>) -> SpanNearQuery {
Changed in a03286ec61e43560c4f56eaada94eb2e7896f997

2022-07-01 11:00 UTC, buinauskas commented on src/search/queries/span/span_near.rs
> +/// TODO
OK, I have not thought about that. I'll check that myself if it's something I can actually do.

2022-07-01 11:52 UTC, buinauskas commented on src/search/queries/span/span_not.rs
> +        exclude: Vec<SpanQuery>,
To make public api easier to use, you could accept anything that can be converted into iterator and its item is convertible to a span query:
```
pub fn span_not<E, I>(exclude: E, include: I) -> SpanNotQuery
where
E: IntoIterator,
E::Item: Into<SpanQuery>,
I: IntoIterator,
I::Item: Into<SpanQuery>,    
{
    let exclude = exclude.into_iter().map(Into::into).collect();
    let include = include.into_iter().map(Into::into).collect();

    todo!()
}
```

this way caller will be able to supply a vector, array, slice, set, a custom iterator of their own.

2022-07-01 11:53 UTC, buinauskas commented on src/search/queries/term_level/regexp_query.rs
> +        where
This looks like an unrelated change.

2022-07-01 11:57 UTC, buinauskas commented
Things look pretty sharp, I believe you got the logic nailed, so these are the common changes across all of the queries:
- Make sure to implement `ShouldSkip` correctly for queries that contain a collection of subqueries, e.g. `SpanNotQuery`, it's better to skip them
- Default to `None` for optional parameters, rely on setters. This gives a more pleasant DSL to use without requiring to specify a lot of default params
- Prefer to accept traits that query can be implemented From<_> something, this allows to have a more concise syntax and experience

I'm overall really happy with this contribution, there might be things that will need some slight tweaking, but they're not obvious right now. I'll approve this once you're confident with the changes.

2022-07-13 09:17 UTC, buinauskas commented
FYI this will impact your changes https://github.com/vinted/elasticsearch-dsl-rs/pull/160 slightly.

2022-12-03 16:37 UTC, buinauskas commented
I figured this is already obsolete and no longer in progress, so I've taken your work and implemented span queries myself in https://github.com/vinted/elasticsearch-dsl-rs/pull/207.

Thank you 🙇🏻

2022-12-03 16:38 UTC, buinauskas commented
I figured this is already obsolete and no longer in progress, so I've taken your work and implemented span queries myself in https://github.com/vinted/elasticsearch-dsl-rs/pull/207.

Thank you 🙇🏻

2022-12-03 16:38 UTC, closed without merging